version: "3.3"

services:
  fast-api-app:
    build: ./app/
    environment:
      DB_USERNAME: ${DOCKER_DB_USERNAME}
      DB_USER_PASSWORD: ${DOCKER_DB_USER_PASSWORD}
      DB_HOST: ${DOCKER_DB_HOST}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      SQLITE_DATABASE: ${SQLITE_DATABASE}
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    
    
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DOCKER_DB_USER_PASSWORD}
      
    ports:
      - "3307:3306"