version: "3.3"

services:
  fast-api:
    build: .
    environment:
      DB_USERNAME: 'root'
      DB_USER_PASSWORD: 'root'
      DB_HOST: 'mysql'
      DB_NAME: 'fast_api'
      SECRET_KEY: 'c99e70f04e8df7e36c6564e5145c0f0f47d157c1b89266821320788ebf4b30c9'
      SQLITE_DATABASE: 'sqlite:///./test.db'
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    
    
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'fast_api'
      MYSQL_ROOT_PASSWORD: 'root'
      
    ports:
      - "3307:3306"